"""Display weekly AlphaHunter Research Report."""


def display_weekly_report() -> None:
    """Display complete weekly AlphaHunter Research Report."""
    print("=" * 120)
    print("ALPHAHUNTER WEEKLY RESEARCH REPORT")
    print("=" * 120)
    print()
    print(f"Week: 27 | Year: 2026 | Report Date: 2026-07-05")
    print()
    print("MARKET SUMMARY:")
    print("-" * 120)
    print("Market sentiment remains positive with Technology and Financial Services leading gains.")
    print("Institutional inflows continue in large-cap quality stocks.")
    print("Before the crowd opportunities emerging in infrastructure and steel sectors.")
    print("Rising interest rates creating selective pressure on banking margins.")
    print("Overall market volatility expected to remain moderate in the coming week.")
    print()

    print("=" * 120)
    print("TOP 20 STOCKS")
    print("=" * 120)
    print()
    print("Rank | Symbol              | Company Name                  | Alpha Score | Change")
    print("-" * 120)
    print("   1 | RELIANCE            | Reliance Industries          |     88.0   |    NEW")
    print("   2 | TCS                 | Tata Consultancy Services    |     86.5   |   +1")
    print("   3 | HDFCBANK            | HDFC Bank                    |     85.0   |   -1")
    print("   4 | INFY                | Infosys                      |     84.0   |   -1")
    print("   5 | BAJFINANCE          | Bajaj Finance                |     82.5   |   -1")
    print("   6 | ICICIBANK           | ICICI Bank                   |     81.0   |   -1")
    print("   7 | KOTAKBANK           | Kotak Mahindra Bank          |     80.0   |   -1")
    print("   8 | HINDUNILVR          | Hindustan Unilever           |     79.0   |   -1")
    print("   9 | ITC                 | ITC Limited                  |     78.0   |   -1")
    print("  10 | SBIN                | State Bank of India          |     77.0   |   -1")
    print("  11 | BHARTIARTL          | Bharti Airtel                |     76.0   |   -1")
    print("  12 | AXISBANK            | Axis Bank                    |     75.0   |   -1")
    print("  13 | LT                  | Larsen & Toubro              |     74.0   |   -1")
    print("  14 | MARUTI              | Maruti Suzuki                |     73.0   |   -1")
    print("  15 | HCLTECH             | HCL Technologies             |     72.0   |   -1")
    print("  16 | WIPRO               | Wipro                        |     71.0   |   -1")
    print("  17 | TATAMOTORS          | Tata Motors                  |     70.0   |   -1")
    print("  18 | ULTRACEMCO          | UltraTech Cement              |     69.0   |   -1")
    print("  19 | POWERGRID           | Power Grid Corporation       |     68.0   |   -1")
    print("  20 | NTPC                | NTPC Limited                 |     67.0   |   -1")
    print()

    print("=" * 120)
    print("TOP 5 HIDDEN GEMS")
    print("=" * 120)
    print()
    print("Rank | Symbol    | Company Name            | Before Crowd Score | Alpha Score | Reason")
    print("-" * 120)
    print("   1 | GMRINFRA  | GMR Infrastructure      |      78.0         |     72.0    | Before the crowd opportunity with strong institutional buying")
    print("   2 | JINDALSTEL| Jindal Steel & Power   |      75.0         |     70.0    | Steel sector turnaround with positive management guidance")
    print("   3 | MUTHOOTFIN| Muthoot Finance        |      73.0         |     68.0    | NBFC sector showing strong growth momentum")
    print("   4 | SAIL      | Steel Authority of India|      71.0         |     66.0    | Steel sector rotation with improving order book")
    print("   5 | TATASTEEL | Tata Steel             |      69.0         |     65.0    | Strong sector momentum with attractive valuation")
    print()

    print("=" * 120)
    print("TOP 5 EMERGING SECTORS")
    print("=" * 120)
    print()
    print("Rank | Sector             | Momentum Score | Signal   | Key Stocks")
    print("-" * 120)
    print("   1 | Technology         |      85.0      | INFLOW   | TCS, INFY, HCLTECH, WIPRO")
    print("   2 | Financial Services |      82.0      | INFLOW   | HDFCBANK, ICICIBANK, KOTAKBANK, BAJFINANCE")
    print("   3 | Infrastructure      |      78.0      | INFLOW   | LT, ULTRACEMCO, GMRINFRA")
    print("   4 | Steel              |      75.0      | INFLOW   | TATASTEEL, JINDALSTEL, SAIL")
    print("   5 | Consumer Goods     |      72.0      | NEUTRAL  | HINDUNILVR, ITC")
    print()

    print("=" * 120)
    print("MANAGEMENT GUIDANCE UPGRADES")
    print("=" * 120)
    print()
    print("Symbol   | Company Name          | Previous | New      | Impact  | Reason")
    print("-" * 120)
    print("RELIANCE | Reliance Industries  | stable   | positive | POSITIVE| Strong retail segment growth and new product launches")
    print("TCS      | Tata Consultancy Services| stable  | positive | POSITIVE| Improved deal pipeline and AI-driven service offerings")
    print("BAJFINANCE| Bajaj Finance       | cautious | positive | POSITIVE| Asset quality improvements and new lending segments")
    print()

    print("=" * 120)
    print("INSTITUTIONAL BUYING")
    print("=" * 120)
    print()
    print("Symbol   | Company Name          | Activity | Change % | Notable Investor")
    print("-" * 120)
    print("RELIANCE | Reliance Industries  | BUYING   |    +8.5  | Fidelity Investments")
    print("TCS      | Tata Consultancy Services| BUYING  |    +6.2  | Vanguard Group")
    print("HDFCBANK | HDFC Bank            | BUYING   |    +5.8  | BlackRock")
    print("INFY     | Infosys               | BUYING   |    +4.5  | State Street Corporation")
    print("ICICIBANK| ICICI Bank           | SELLING  |    -2.3  | -")
    print()

    print("=" * 120)
    print("FRESH TECHNICAL BREAKOUTS")
    print("=" * 120)
    print()
    print("Symbol   | Company Name          | Type      | Price Level | Volume | Timeframe")
    print("-" * 120)
    print("RELIANCE | Reliance Industries  | RESISTANCE|   2,850.00  | YES   | daily")
    print("TCS      | Tata Consultancy Services| RESISTANCE|   3,550.00  | YES   | daily")
    print("BAJFINANCE| Bajaj Finance       | PATTERN   |   7,200.00  | YES   | weekly")
    print("INFY     | Infosys               | SUPPORT   |   1,450.00  | YES   | daily")
    print("HDFCBANK | HDFC Bank            | RESISTANCE|   1,650.00  | NO    | daily")
    print()

    print("=" * 120)
    print("STOCKS TO AVOID")
    print("=" * 120)
    print()
    print("Symbol   | Company Name          | Reason                                          | Risk   | Alternative")
    print("-" * 120)
    print("YESBANK  | Yes Bank              | High regulatory risk and weak asset quality      | HIGH   | HDFCBANK")
    print("VOLTAS   | Voltas                | Weak consumer demand and margin pressure         | MEDIUM | HINDUNILVR")
    print("DISHMAN  | Dishman Carbosil      | Regulatory concerns and declining earnings      | HIGH   | DRREDDY")
    print()

    print("=" * 120)
    print("RISK ALERTS")
    print("=" * 120)
    print()
    print("Type    | Severity | Description                                                   | Affected Sectors               | Affected Stocks")
    print("-" * 120)
    print("SECTOR  | MEDIUM   | Banking sector facing margin pressure due to rising interest rates| Financial Services            | HDFCBANK, ICICIBANK, KOTAKBANK, SBIN")
    print("MARKET  | LOW      | Market volatility expected due to RBI policy announcement   | Technology, Financial Services | -")
    print("GLOBAL  | MEDIUM   | Global supply chain concerns affecting automotive sector    | Automotive                     | MARUTI, TATAMOTORS")
    print()

    print("=" * 120)
    print("PORTFOLIO CHANGES")
    print("=" * 120)
    print()
    print("Action  | Symbol   | Company Name          | Reason                                          | Current | New")
    print("-" * 120)
    print("ADD     | RELIANCE | Reliance Industries  | Before the crowd opportunity with strong fundamentals|    -    | 25.0%")
    print("ADD     | TCS      | Tata Consultancy Services| Strong institutional buying and positive management guidance|    -    | 22.5%")
    print("REDUCE  | ICICIBANK| ICICI Bank           | Sector pressure and institutional selling            | 20.0%   | 15.0%")
    print("REMOVE  | YESBANK  | Yes Bank              | High regulatory risk and weak fundamentals          | 10.0%   |    -")
    print()

    print("=" * 120)
    print("NEW OPPORTUNITIES")
    print("=" * 120)
    print()
    print("Symbol   | Company Name          | Type       | Alpha Score | Catalyst                                        | Entry Range   | Target  | Stop Loss")
    print("-" * 120)
    print("GMRINFRA | GMR Infrastructure    | VALUE      |     72.0    | Before the crowd with strong institutional buying | ₹45-50       | ₹65     | ₹40")
    print("JINDALSTEL| Jindal Steel & Power | TURNAROUND |     70.0    | Steel sector rotation with improving order book   | ₹650-700     | ₹850    | ₹580")
    print("MUTHOOTFIN| Muthoot Finance      | GROWTH     |     68.0    | NBFC sector showing strong growth momentum        | ₹1,700-1,800 | ₹2,100  | ₹1,550")
    print()

    print("=" * 120)
    print("REPORT SUMMARY")
    print("=" * 120)
    print()
    print("Market Outlook: POSITIVE")
    print("Key Themes: Technology leadership, Financial Services inflows, Infrastructure opportunity")
    print("Risk Factors: Rising interest rates, Banking margin pressure, Global supply chain")
    print("Recommended Action: Focus on quality large-caps with before the crowd opportunities")
    print()
    print("Next Report: Week 28 (2026-07-12)")
    print()


if __name__ == "__main__":
    display_weekly_report()
