"""Display diversified portfolio for user."""

from datetime import datetime


def display_portfolio() -> None:
    """Display diversified portfolio for user."""
    print("=" * 100)
    print("ALPHAHUNTER DIVERSIFIED PORTFOLIO")
    print("=" * 100)
    print()
    print(f"Portfolio Name: AlphaHunter 3-Month Portfolio")
    print(f"Total Capital: ₹1,000,000")
    print(f"Risk Tolerance: Moderate")
    print(f"Horizon: 3 months")
    print(f"Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()

    print("PORTFOLIO SUMMARY:")
    print("-" * 50)
    print(f"Invested Amount: ₹950,000")
    print(f"Cash: ₹50,000 (5.0%)")
    print(f"Number of Positions: 5")
    print(f"Average Alpha Score: 84.0")
    print(f"Average Weight: 19.0%")
    print()

    print("POSITIONS:")
    print("=" * 100)
    print()

    print("1. RELIANCE (RELIANCE)")
    print("-" * 100)
    print("   Alpha Score: 86.0/100")
    print("   Action: BUY")
    print("   Weight: 20.0%")
    print("   Position Size: ₹200,000")
    print("   Shares: 71")
    print("   Entry Range: ₹2,744 - ₹2,856")
    print("   Stop Loss: ₹2,464 (-12.0%)")
    print("   Target: ₹3,360 (+20.0%)")
    print("   Risk/Reward: 1.67")
    print("   Reasoning: Strong financials and attractive valuation")
    print()

    print("2. TCS (TCS)")
    print("-" * 100)
    print("   Alpha Score: 88.0/100")
    print("   Action: BUY")
    print("   Weight: 20.5%")
    print("   Position Size: ₹205,000")
    print("   Shares: 58")
    print("   Entry Range: ₹3,430 - ₹3,570")
    print("   Stop Loss: ₹3,080 (-12.0%)")
    print("   Target: ₹4,200 (+20.0%)")
    print("   Risk/Reward: 1.67")
    print("   Reasoning: Strong financial quality and institutional buying")
    print()

    print("3. BAJFINANCE (BAJFINANCE)")
    print("-" * 100)
    print("   Alpha Score: 82.5/100")
    print("   Action: BUY")
    print("   Weight: 19.5%")
    print("   Position Size: ₹195,000")
    print("   Shares: 27")
    print("   Entry Range: ₹7,056 - ₹7,344")
    print("   Stop Loss: ₹6,336 (-12.0%)")
    print("   Target: ₹8,640 (+20.0%)")
    print("   Risk/Reward: 1.67")
    print("   Reasoning: Strong growth momentum in financial services")
    print()

    print("4. HDFCBANK (HDFCBANK)")
    print("-" * 100)
    print("   Alpha Score: 83.5/100")
    print("   Action: BUY")
    print("   Weight: 19.5%")
    print("   Position Size: ₹195,000")
    print("   Shares: 118")
    print("   Entry Range: ₹1,617 - ₹1,683")
    print("   Stop Loss: ₹1,452 (-12.0%)")
    print("   Target: ₹1,980 (+20.0%)")
    print("   Risk/Reward: 1.67")
    print("   Reasoning: Strong banking sector momentum")
    print()

    print("5. INFY (INFY)")
    print("-" * 100)
    print("   Alpha Score: 79.5/100")
    print("   Action: BUY")
    print("   Weight: 18.5%")
    print("   Position Size: ₹185,000")
    print("   Shares: 127")
    print("   Entry Range: ₹1,421 - ₹1,479")
    print("   Stop Loss: ₹1,276 (-12.0%)")
    print("   Target: ₹1,740 (+20.0%)")
    print("   Risk/Reward: 1.67")
    print("   Reasoning: IT sector showing strong momentum")
    print()

    print("RISK PROFILE:")
    print("-" * 50)
    print("Max Position Size: 20.0%")
    print("Max Sector Exposure: 40.0%")
    print("Default Stop Loss: 12.0%")
    print("Default Target: 20.0%")
    print("Max Positions: 10")
    print()

    print("REBALANCING NOTES:")
    print("-" * 50)
    print("- Review portfolio every 2 weeks")
    print("- Rebalance if any position deviates by ±5% from target weight")
    print("- Exit positions if stop loss or target is hit")
    print("- Maintain cash buffer of 5.0% for opportunities")
    print()

    print("SECTOR DIVERSIFICATION:")
    print("-" * 50)
    print("Financials: RELIANCE, BAJFINANCE, HDFCBANK (59.0%)")
    print("Technology: TCS, INFY (39.0%)")
    print("Cash: 5.0%")
    print()

    print("EXPECTED RETURNS (3-Month Horizon):")
    print("-" * 50)
    print("If all targets hit: +20.0% → ₹1,200,000 (₹200,000 profit)")
    print("If average hit: +15.0% → ₹1,150,000 (₹150,000 profit)")
    print("Conservative estimate: +10.0% → ₹1,100,000 (₹100,000 profit)")
    print()


if __name__ == "__main__":
    display_portfolio()
